version: "3.2"

services:
  mysql:
    image: "${DIPLOMA_MYSQL_IMAGE}"
    container_name: "${DIPLOMA_MYSQL_CONTAINER}"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
        - ./init.sql:/data/application/init.sql
    ports: 
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=diploma
      # - MYSQL_USER=diploma
      # - MYSQL_PASSWORD=root

    networks:
      - diploma-network

networks:
  diploma-network:
    external:
      name: diploma-network