version: "3.2"

services:

  mysql:
    image: "${DIPLOMA_MYSQL_IMAGE}"
    container_name: "${DIPLOMA_MYSQL_CONTAINER}"
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports: 
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=diploma
      # - MYSQL_USER=diploma
      # - MYSQL_PASSWORD=root

    # networks:
    #   - diploma-network

  frontend:
    image: "${DIPLOMA_FRONTEND_IMAGE}"
    container_name: "${DIPLOMA_FRONTEND_CONTAINER}"
    user: "node"
    working_dir: /home/node/app
    stdin_open: true
    volumes:
      - "${DIPLOMA_FRONTEND_PATH}:/home/node/app"
    ports:
      - "3000:3000"

networks:
  diploma-network:
    external:
      name: diploma-network