POST http://localhost:3005/auth/register
content-type: application/json

    {
        "username": "Alexey",
        "password": "lolw",
        "email": "alexey-032@yandex.ru",
        "difficulty_level": "1"
    }

###

POST http://localhost:3005/auth/login
content-type: application/json

    {
        "email": "alexey-032@yandex.ru",
        "password": "lolw"
    }