POST http://localhost:3005/auth/register
content-type: application/json

    {
        "username": "Alexey",
        "password": "lolw",
        "email": "alexey-032@yandex.rudd",
        "difficulty_level": "1"
    }

###

POST http://localhost:3005/auth/login
content-type: application/json

    {
        "email": "alexey-032@yandex.rudd",
        "password": "lolw"
    }

###

GET http://localhost:3005/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjksImlhdCI6MTYxOTMzODIwNiwiZXhwIjoxNjE5MzQ1NDA2fQ.EqwHLqYoh5163tPJZcgT8Z5NFPQBsJJfrFI95JOfxKE
content-type: application/json